/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as PostsRouteRouteImport } from "./routes/posts/route";
import { Route as AppRouteRouteImport } from "./routes/_app/route";
import { Route as AppIndexRouteImport } from "./routes/_app/index";
import { Route as PostsPostIdRouteImport } from "./routes/posts/$postId";
import { Route as DevUiRouteImport } from "./routes/dev/ui";
import { Route as AppTodoRouteImport } from "./routes/_app/todo";
import { Route as AppAboutRouteImport } from "./routes/_app/about";
import { Route as PostsCategoryChar123CategoryChar125RouteImport } from "./routes/posts/category.{-$category}";

const PostsRouteRoute = PostsRouteRouteImport.update({
  id: "/posts",
  path: "/posts",
  getParentRoute: () => rootRouteImport,
} as any);
const AppRouteRoute = AppRouteRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any);
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRouteRoute,
} as any);
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: "/$postId",
  path: "/$postId",
  getParentRoute: () => PostsRouteRoute,
} as any);
const DevUiRoute = DevUiRouteImport.update({
  id: "/dev/ui",
  path: "/dev/ui",
  getParentRoute: () => rootRouteImport,
} as any);
const AppTodoRoute = AppTodoRouteImport.update({
  id: "/todo",
  path: "/todo",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppAboutRoute = AppAboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => AppRouteRoute,
} as any);
const PostsCategoryChar123CategoryChar125Route =
  PostsCategoryChar123CategoryChar125RouteImport.update({
    id: "/category/{-$category}",
    path: "/category/{-$category}",
    getParentRoute: () => PostsRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute;
  "/posts": typeof PostsRouteRouteWithChildren;
  "/about": typeof AppAboutRoute;
  "/todo": typeof AppTodoRoute;
  "/dev/ui": typeof DevUiRoute;
  "/posts/$postId": typeof PostsPostIdRoute;
  "/posts/category/{-$category}": typeof PostsCategoryChar123CategoryChar125Route;
}
export interface FileRoutesByTo {
  "/posts": typeof PostsRouteRouteWithChildren;
  "/about": typeof AppAboutRoute;
  "/todo": typeof AppTodoRoute;
  "/dev/ui": typeof DevUiRoute;
  "/posts/$postId": typeof PostsPostIdRoute;
  "/": typeof AppIndexRoute;
  "/posts/category/{-$category}": typeof PostsCategoryChar123CategoryChar125Route;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_app": typeof AppRouteRouteWithChildren;
  "/posts": typeof PostsRouteRouteWithChildren;
  "/_app/about": typeof AppAboutRoute;
  "/_app/todo": typeof AppTodoRoute;
  "/dev/ui": typeof DevUiRoute;
  "/posts/$postId": typeof PostsPostIdRoute;
  "/_app/": typeof AppIndexRoute;
  "/posts/category/{-$category}": typeof PostsCategoryChar123CategoryChar125Route;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/posts"
    | "/about"
    | "/todo"
    | "/dev/ui"
    | "/posts/$postId"
    | "/posts/category/{-$category}";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/posts"
    | "/about"
    | "/todo"
    | "/dev/ui"
    | "/posts/$postId"
    | "/"
    | "/posts/category/{-$category}";
  id:
    | "__root__"
    | "/_app"
    | "/posts"
    | "/_app/about"
    | "/_app/todo"
    | "/dev/ui"
    | "/posts/$postId"
    | "/_app/"
    | "/posts/category/{-$category}";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren;
  PostsRouteRoute: typeof PostsRouteRouteWithChildren;
  DevUiRoute: typeof DevUiRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/posts": {
      id: "/posts";
      path: "/posts";
      fullPath: "/posts";
      preLoaderRoute: typeof PostsRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AppRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/": {
      id: "/_app/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AppIndexRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/posts/$postId": {
      id: "/posts/$postId";
      path: "/$postId";
      fullPath: "/posts/$postId";
      preLoaderRoute: typeof PostsPostIdRouteImport;
      parentRoute: typeof PostsRouteRoute;
    };
    "/dev/ui": {
      id: "/dev/ui";
      path: "/dev/ui";
      fullPath: "/dev/ui";
      preLoaderRoute: typeof DevUiRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/todo": {
      id: "/_app/todo";
      path: "/todo";
      fullPath: "/todo";
      preLoaderRoute: typeof AppTodoRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/about": {
      id: "/_app/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AppAboutRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/posts/category/{-$category}": {
      id: "/posts/category/{-$category}";
      path: "/category/{-$category}";
      fullPath: "/posts/category/{-$category}";
      preLoaderRoute: typeof PostsCategoryChar123CategoryChar125RouteImport;
      parentRoute: typeof PostsRouteRoute;
    };
  }
}

interface AppRouteRouteChildren {
  AppAboutRoute: typeof AppAboutRoute;
  AppTodoRoute: typeof AppTodoRoute;
  AppIndexRoute: typeof AppIndexRoute;
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppTodoRoute: AppTodoRoute,
  AppIndexRoute: AppIndexRoute,
};

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(AppRouteRouteChildren);

interface PostsRouteRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRoute;
  PostsCategoryChar123CategoryChar125Route: typeof PostsCategoryChar123CategoryChar125Route;
}

const PostsRouteRouteChildren: PostsRouteRouteChildren = {
  PostsPostIdRoute: PostsPostIdRoute,
  PostsCategoryChar123CategoryChar125Route: PostsCategoryChar123CategoryChar125Route,
};

const PostsRouteRouteWithChildren = PostsRouteRoute._addFileChildren(PostsRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  PostsRouteRoute: PostsRouteRouteWithChildren,
  DevUiRoute: DevUiRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
