packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@mdx-js/rollup": ^3.1.1
  "@rolldown/plugin-babel": ^0.2.2
  "@tailwindcss/vite": ^4.2.2
  "@tanstack/react-router": ^1.168.10
  "@tanstack/react-router-devtools": ^1.166.11
  "@tanstack/router-plugin": ^1.167.12
  "@types/node": ^24
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  "@vitejs/plugin-react": ^6.0.1
  babel-plugin-react-compiler: ^1.0.0
  react: ^19.2.4
  react-dom: ^19.2.4
  redaxios: ^0.5.1
  tailwindcss: ^4.2.2
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  zod: ^4.3.6

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
