shellEmulator: true

trustPolicy: experimental
packages:
  - apps/*
  - packages/*

overrides:
  vite: npm:rolldown-vite@7.2.5
catalog:
  '@hookform/resolvers': ^5.2.2
  '@lingui/core': ^5.9.0
  '@lingui/react': ^5.9.0
  '@streamdown/cjk': ^1.0.2
  '@streamdown/code': ^1.0.2
  '@streamdown/math': ^1.0.2
  '@streamdown/mermaid': ^1.0.2
  '@tanstack/react-query': ^5.90.21
  ai: ^6.0.85
  axios: ^1.13.5
  immer: ^11.1.3
  nanoid: ^5.1.6
  react: ^19.2.4
  react-dom: ^19.2.3
  react-hook-form: ^7.71.1
  react-router: ^7.12.0
  streamdown: ^2.2.0
  zod: ^4.3.6
  zustand: ^5.0.10
catalogs:
  dev:
    '@lingui/babel-plugin-lingui-macro': 5.9.0
    '@lingui/cli': ^5.9.0
    '@lingui/vite-plugin': ^5.9.0
    '@tailwindcss/vite': ^4.1.18
    '@types/node': ^24.10.9
    '@types/react': ^19.2.8
    '@types/react-dom': ^19.2.3
    '@vitejs/plugin-react': ^5.1.2
    babel-plugin-react-compiler: ^1.0.0
    globals: ^16.5.0
    msw: ^2.12.10
    turbo: ^2.8.1
    typescript: ~5.9.3
    typescript-eslint: ^8.53.0
    vite: npm:rolldown-vite@7.2.5
  lint:
    '@antfu/eslint-config': ^7.0.1
    '@eslint-react/eslint-plugin': ^2.7.2
    '@eslint/js': ^9.39.2
    eslint: ^9.39.2
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.26
  ui:
    '@base-ui/react': 1.2.0
    '@floating-ui/react': ^0.27.17
    '@next/third-parties': ^16.1.6
    '@radix-ui/react-accordion': ^1.2.12
    '@radix-ui/react-alert-dialog': ^1.1.15
    '@radix-ui/react-aspect-ratio': ^1.1.8
    '@radix-ui/react-avatar': ^1.1.11
    '@radix-ui/react-checkbox': ^1.3.3
    '@radix-ui/react-collapsible': ^1.1.12
    '@radix-ui/react-context-menu': ^2.2.16
    '@radix-ui/react-dialog': ^1.1.15
    '@radix-ui/react-dropdown-menu': ^2.1.16
    '@radix-ui/react-hover-card': ^1.1.15
    '@radix-ui/react-label': ^2.1.8
    '@radix-ui/react-menubar': ^1.1.16
    '@radix-ui/react-navigation-menu': ^1.2.14
    '@radix-ui/react-popover': ^1.1.15
    '@radix-ui/react-progress': ^1.1.8
    '@radix-ui/react-radio-group': ^1.3.8
    '@radix-ui/react-scroll-area': ^1.2.10
    '@radix-ui/react-select': ^2.2.6
    '@radix-ui/react-separator': ^1.1.8
    '@radix-ui/react-slider': ^1.3.6
    '@radix-ui/react-slot': ^1.2.4
    '@radix-ui/react-switch': ^1.2.6
    '@radix-ui/react-tabs': ^1.1.13
    '@radix-ui/react-toggle': ^1.1.10
    '@radix-ui/react-toggle-group': ^1.1.11
    '@radix-ui/react-tooltip': ^1.2.8
    '@radix-ui/react-use-controllable-state': ^1.2.2
    '@radix-ui/react-visually-hidden': ^1.2.4
    '@react-three/fiber': ^9.5.0
    '@react-three/postprocessing': ^3.0.4
    '@rive-app/react-webgl2': ^4.26.2
    '@tabler/icons': ^3.36.1
    '@tabler/icons-react': ^3.36.1
    '@toolwind/corner-shape': ^0.0.8-3
    '@types/three': ^0.182.0
    '@wandry/analytics-sdk': ^1.16.0
    '@xyflow/react': ^12.10.0
    ansi-to-react: ^6.2.6
    class-variance-authority: ^0.7.1
    clsx: ^2.1.1
    cmdk: ^1.1.1
    date-fns: ^4.1.0
    embla-carousel-react: ^8.6.0
    input-otp: ^1.4.2
    js-yaml: ^4.1.1
    lucide-react: ^0.562.0
    media-chrome: ^4.17.2

    motion: ^12.29.2
    next: ^16.1.6
    next-sitemap: ^4.2.3
    next-themes: ^0.4.6
    nuqs: ^2.8.7
    postprocessing: ^6.38.2
    radix-ui: ^1.4.3
    react-day-picker: ^9.13.0
    react-grab: ^0.0.98
    react-jsx-parser: ^2.4.1
    react-markdown: ^10.1.0
    react-resizable-panels: ^4.5.6
    recharts: ^3.7.0
    rehype-raw: ^7.0.0
    remark-gfm: ^4.0.1
    shadcn: ^3.8.1
    shiki: ^3.22.0
    sonner: ^2.0.7
    tailwind-merge: ^3.4.0
    tailwindcss: ^4.1.18
    three: ^0.182.0
    tokenlens: ^1.3.1
    tw-animate-css: ^1.4.0
    ultracite: ^7.1.1
    use-stick-to-bottom: ^1.1.3
    vaul: ^1.1.2
onlyBuiltDependencies:
  - esbuild
