/**
 * Icon generator — reads icons.config.mjs and generates TSX components + index.ts
 *
 * Usage:
 *   tsx scripts/gen-icons.ts                  # generate all from config
 *   tsx scripts/gen-icons.ts --force          # overwrite without prompting
 */

import { join, dirname } from "path";
import { fileURLToPath, pathToFileURL } from "url";
import { createInterface } from "readline";
import fs from "fs-extra";
import { glob } from "tinyglobby";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const componentsDir = join(root, "src/components");
const indexFile = join(root, "src/index.ts");
const force = process.argv.includes("--force");

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type IconEntry = { componentName: string; collection: string; iconName: string };
type IconData = { body: string; width?: number; height?: number };
type CollectionData = { icons: Record<string, IconData> };
type IconConfig = Array<string | Record<string, string>>;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const toPascal = (str: string) =>
  str
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");

const deriveComponentName = (source: string) => toPascal(source.split(":")[1]) + "Icon";

async function findIconifyJson(collection: string): Promise<string> {
  const workspaceRoot = join(root, "../..");

  const candidates = [
    join(workspaceRoot, "node_modules/@iconify/json/json", `${collection}.json`),
    join(root, "node_modules/@iconify/json/json", `${collection}.json`),
  ];
  for (const p of candidates) {
    if (await fs.pathExists(p)) return p;
  }

  const matches = await glob(
    `node_modules/.pnpm/@iconify+json@*/node_modules/@iconify/json/json/${collection}.json`,
    { cwd: workspaceRoot, absolute: true },
  );
  if (matches.length > 0) return matches[0];

  throw new Error(
    `@iconify/json collection "${collection}" not found.\n` +
      `Make sure @iconify/json is installed in the workspace.`,
  );
}

const collectionCache: Record<string, CollectionData> = {};
async function getIcon(collection: string, iconName: string): Promise<IconData | null> {
  if (!collectionCache[collection]) {
    const p = await findIconifyJson(collection);
    collectionCache[collection] = await fs.readJson(p);
  }
  return collectionCache[collection].icons[iconName] ?? null;
}

async function confirm(question: string): Promise<boolean> {
  if (force) return true;
  const rl = createInterface({ input: process.stdin, output: process.stdout });
  return new Promise((resolve) => {
    rl.question(`${question} (y/N) `, (answer) => {
      rl.close();
      resolve(answer.toLowerCase() === "y");
    });
  });
}

const SVG_ATTR_MAP: Record<string, string> = {
  "stroke-linecap": "strokeLinecap",
  "stroke-linejoin": "strokeLinejoin",
  "stroke-width": "strokeWidth",
  "fill-rule": "fillRule",
  "clip-rule": "clipRule",
  "fill-opacity": "fillOpacity",
  "stroke-opacity": "strokeOpacity",
};

const fixSvgAttrs = (body: string) =>
  Object.entries(SVG_ATTR_MAP).reduce((s, [from, to]) => s.replaceAll(from, to), body);

const generateTsx = (componentName: string, body: string) =>
  `import type { SVGProps } from 'react'

export function ${componentName}(props: SVGProps<SVGSVGElement>) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" {...props}>
      ${fixSvgAttrs(body)}
    </svg>
  )
}
export default ${componentName}
`;

async function generateIndex(): Promise<number> {
  const files = (await glob("*.tsx", { cwd: componentsDir })).sort();

  const lines = [
    "// Auto-generated by scripts/gen-icons.ts — do not edit manually",
    "",
    ...files.map((f) => {
      const name = f.replace(".tsx", "");
      return `export { ${toPascal(name)}Icon } from './components/${name}'`;
    }),
    "",
  ];

  await fs.outputFile(indexFile, lines.join("\n"));
  return files.length;
}

// ---------------------------------------------------------------------------
// Parse config
// ---------------------------------------------------------------------------

function parseConfig(config: IconConfig): IconEntry[] {
  const entries: IconEntry[] = [];
  for (const item of config) {
    if (typeof item === "string") {
      const [collection, iconName] = item.split(":");
      entries.push({ componentName: deriveComponentName(item), collection, iconName });
    } else {
      for (const [componentName, source] of Object.entries(item)) {
        const [collection, iconName] = source.split(":");
        entries.push({ componentName, collection, iconName });
      }
    }
  }
  return entries;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

await fs.ensureDir(componentsDir);

const config: IconConfig = (await import(pathToFileURL(join(root, "icons.config.mjs")).href))
  .default;
const entries = parseConfig(config);

let generated = 0,
  skipped = 0,
  errors = 0;

for (const { componentName, collection, iconName } of entries) {
  const fileName = componentName
    .replace(/Icon$/, "")
    .replace(/([A-Z])/g, (_, c: string, i: number) =>
      i === 0 ? c.toLowerCase() : `-${c.toLowerCase()}`,
    );

  const filePath = join(componentsDir, `${fileName}.tsx`);

  if ((await fs.pathExists(filePath)) && !force) {
    const overwrite = await confirm(
      `"${fileName}.tsx" already exists (${componentName}). Overwrite?`,
    );
    if (!overwrite) {
      skipped++;
      continue;
    }
  }

  const icon = await getIcon(collection, iconName);
  if (!icon) {
    console.error(`  ✗ Not found: ${collection}:${iconName}`);
    errors++;
    continue;
  }

  await fs.outputFile(filePath, generateTsx(componentName, icon.body));
  console.log(`  ✓ ${fileName}.tsx  (${collection}:${iconName})`);
  generated++;
}

const total = await generateIndex();

console.log(`\nDone: ${generated} generated, ${skipped} skipped, ${errors} errors`);
console.log(`index.ts updated with ${total} icons`);
