/**
 * Index generator — scans src/components/*.tsx and regenerates src/index.ts
 * Useful when icons are added/edited manually without running gen-icons.ts
 *
 * Usage: tsx scripts/gen-index.ts
 */

import { join, dirname } from "path";
import { fileURLToPath } from "url";
import fs from "fs-extra";
import { glob } from "tinyglobby";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const componentsDir = join(root, "src/components");
const indexFile = join(root, "src/index.ts");

const toPascal = (str: string) =>
  str
    .split(/[-_]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");

const files = (await glob("*.tsx", { cwd: componentsDir })).sort();

const lines = [
  "// Auto-generated by scripts/gen-index.ts — do not edit manually",
  "",
  ...files.map((f) => {
    const name = f.replace(".tsx", "");
    return `export { ${toPascal(name)}Icon } from './components/${name}'`;
  }),
  "",
];

await fs.outputFile(indexFile, lines.join("\n"));
console.log(`index.ts updated with ${files.length} icons`);
